"""Shared PDF helpers for SiteIQ, TopoIQ, and YieldIQ reports."""
from __future__ import annotations

import re

from pvmath_brand import PRODUCT_NAME
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import HRFlowable, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm

_EMOJI_PATTERN = re.compile(
    r"[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F600-\U0001F64F"
    r"\u2600-\u26FF\u2700-\u27BF\uFE0F"
    r"✅⚠️❌🟢🟡🟠🔴⚠★]+"
)

SITEIQ_DISCLAIMER_BODY = (
    "This report provides preliminary site screening for internal go/no-go and early "
    "client discussions only. Solar data from PVGIS JRC; terrain from satellite DEM "
    "(indicative unless TopoIQ-confirmed); flood risk is an elevation heuristic, not "
    "hydraulic modelling; regulatory flags are indicative OSM-based checks, not "
    "permitting diligence. PVMath does not claim bankability. A full engineering study, "
    "site survey, permitting review, and certified energy yield assessment are required "
    "before financing, EPC contract, or final investment decision."
)

# Metric definitions for KEY METRICS table — appended to every SiteIQ PDF.
SITEIQ_METRICS_ANNEXURE = [
    (
        "In-plane Irradiation",
        "Annual solar radiation on the module plane (kWh/m²/year), from PVGIS (EC JRC). "
        "Compares solar resource between sites. Screening-grade — not a bankable irradiation study.",
    ),
    (
        "Specific Yield",
        "Estimated annual energy per installed DC kWp (kWh/kWp/year), derived from PVGIS "
        "with standard screening losses (flat loss; no row-to-row shading in SiteIQ). "
        "Use YieldIQ for configuration comparison; use PVsyst or equivalent for bankable yield.",
    ),
    (
        "Optimal Tilt",
        "PVGIS-recommended fixed-tilt angle (degrees) for this location on a south-facing "
        "plane (or local equivalent). Omitted for single-axis tracker screening — tracker "
        "runs on a horizontal N–S axis.",
    ),
    (
        "Max / Mean Slope",
        "Terrain steepness (% grade) from satellite DEM. Max slope uses sparse sample points "
        "unless TopoIQ has been run on the project boundary (then mean and max from "
        "Copernicus GLO-30 grid). Indicative only — not survey-grade topography.",
    ),
    (
        "Elevation",
        "Centre-point elevation above sea level (m) from EU-DEM (Europe) or SRTM (global) "
        "via OpenTopoData. Used for context and flood heuristic — not geodetic survey.",
    ),
    (
        "Flood Risk",
        "Rule-based flag from elevation context — not official flood-zone mapping or "
        "hydraulic modelling. Always verify with local flood products and hydrology "
        "studies before investment decisions.",
    ),
    (
        "Est. DC Capacity",
        "Indicative DC capacity band (MWp) from site area, land-use density (MW/ha), and "
        "ground coverage ratio (GCR) assumptions for the selected mounting type. "
        "Not a layout or interconnection study.",
    ),
    (
        "Est. Output",
        "Indicative annual energy (MWh/year) from screening specific yield × estimated DC "
        "capacity. For early feasibility only — not lender-grade production estimates.",
    ),
    (
        "Incentive / Tariff",
        "Country-aware pointer to typical remuneration or auction frameworks (e.g. EEG, "
        "SECI, PPA). Indicative checklist item — not legal, tax, or tariff advice. "
        "Confirm with local advisors and offtake contracts.",
    ),
]

PVMATH_FOOTER_TEMPLATE = (
    "Generated by {module} — " + PRODUCT_NAME + " "
    "&nbsp;|&nbsp; pvmath.com &nbsp;|&nbsp; contact@pvmath.com "
    "&nbsp;|&nbsp; For professional use only. {note}"
    "Data sources: {sources}."
)


def strip_pdf_label(text: str) -> str:
    """Remove emoji/icons from labels before PDF rendering (Helvetica-safe)."""
    if not text:
        return text
    cleaned = _EMOJI_PATTERN.sub("", str(text))
    return re.sub(r"\s+", " ", cleaned).strip()


def format_siteiq_companion_note(siteiq_run_cache: dict | None) -> str:
    """Rich SiteIQ companion text for TopoIQ PDF when screening cache exists."""
    if not siteiq_run_cache or not siteiq_run_cache.get("solar"):
        return (
            "Run SiteIQ on the same project for solar resource, flood risk, regulatory "
            "pathway, and overall site verdict. Terrain screening is one layer of the "
            "PVMath site intelligence workflow."
        )

    parts = ["SiteIQ screening has been run on this project."]
    score = siteiq_run_cache.get("pvmath_score")
    verdict = siteiq_run_cache.get("pvmath_verdict")
    if score is not None and verdict:
        parts.append(f"PVMath Site Suitability Score: {score}/100 ({verdict}).")

    solar = siteiq_run_cache.get("solar") or {}
    if solar.get("success") and solar.get("annual_ghi"):
        parts.append(f"Annual GHI: {solar['annual_ghi']:.0f} kWh/m²/yr.")

    terrain = siteiq_run_cache.get("terrain") or {}
    if terrain.get("success"):
        if terrain.get("topoiq_confirmed"):
            parts.append(
                f"Terrain (TopoIQ-linked): mean slope {terrain.get('mean_slope_pct', 0):.1f}%, "
                f"max {terrain.get('max_slope_pct', 0):.1f}%."
            )
        elif terrain.get("mean_slope_pct") is not None:
            parts.append(
                f"Terrain (indicative sample): mean slope {terrain['mean_slope_pct']:.1f}%."
            )

    rid = siteiq_run_cache.get("screening_report_id")
    if rid:
        parts.append(f"Screening ID: {rid}.")

    parts.append(
        "Open SiteIQ for flood risk, regulatory pathway, and the full site screening PDF."
    )
    return " ".join(parts)


def append_pdf_disclaimer(
    story,
    body: str,
    *,
    title: str = "IMPORTANT DISCLAIMER",
    border_color: str = "#f0b429",
    bg_color: str = "#fff8e6",
    text_color: str = "#7a4f00",
):
    """Append an amber-style disclaimer callout (YieldIQ pattern)."""
    story.append(Paragraph(
        title,
        ParagraphStyle(
            "disc_title",
            fontSize=9,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor(text_color),
            leading=12,
        ),
    ))
    story.append(Spacer(1, 0.15 * cm))
    disc_tbl = Table([[
        Paragraph(
            body,
            ParagraphStyle(
                "disc_body",
                fontSize=8.5,
                textColor=colors.HexColor(text_color),
                leading=13,
            ),
        ),
    ]], colWidths=["100%"])
    disc_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg_color)),
        ("BOX", (0, 0), (-1, -1), 1.5, colors.HexColor(border_color)),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(disc_tbl)


def append_siteiq_metrics_annexure(
    story,
    *,
    accent_color: str = "#e85d04",
    muted_color: str = "#5a7a5a",
    border_color: str = "#d4e0d4",
    dark_color: str = "#1a2e1a",
):
    """Annex explaining KEY METRICS — included at the bottom of every SiteIQ report."""
    from reportlab.lib.styles import getSampleStyleSheet

    styles = getSampleStyleSheet()
    accent = colors.HexColor(accent_color)
    muted = colors.HexColor(muted_color)
    border = colors.HexColor(border_color)
    dark = colors.HexColor(dark_color)

    hdr = Table(
        [[
            Paragraph("", ParagraphStyle("x", parent=styles["Normal"])),
            Paragraph(
                "ANNEX — SCREENING METRICS EXPLAINED",
                ParagraphStyle(
                    "annex_h",
                    parent=styles["Normal"],
                    fontSize=11,
                    fontName="Helvetica-Bold",
                    textColor=dark,
                    leading=14,
                ),
            ),
        ]],
        colWidths=[0.28 * cm, 16.72 * cm],
    )
    hdr.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), accent),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (1, 0), (1, -1), 8),
        ("LEFTPADDING", (0, 0), (0, -1), 0),
    ]))
    story.append(hdr)
    story.append(Spacer(1, 0.12 * cm))
    story.append(Paragraph(
        "The Key Metrics table rates each parameter for early go/no-go. "
        "Ratings (Excellent, Acceptable, Low risk, etc.) reflect screening thresholds — "
        "not bankability or permitting approval.",
        ParagraphStyle("annex_intro", parent=styles["Normal"], fontSize=8, textColor=muted, leading=11),
    ))
    story.append(Spacer(1, 0.15 * cm))

    def _cell(text, *, bold=False, size=7.5, color=dark):
        return Paragraph(
            strip_pdf_label(str(text)),
            ParagraphStyle(
                "annex_c",
                parent=styles["Normal"],
                fontSize=size,
                fontName="Helvetica-Bold" if bold else "Helvetica",
                textColor=color,
                leading=10,
            ),
        )

    rows = [[_cell("Metric", bold=True, color=colors.white), _cell("What it means", bold=True, color=colors.white)]]
    for metric, definition in SITEIQ_METRICS_ANNEXURE:
        rows.append([_cell(metric, bold=True, size=7.5), _cell(definition, size=7.5, color=muted)])

    tbl = Table(rows, colWidths=[4.2 * cm, 12.8 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), accent),
        ("BOX", (0, 0), (-1, -1), 0.5, border),
        ("INNERGRID", (0, 0), (-1, -1), 0.35, border),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f7f5")]),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.3 * cm))


def append_pdf_footer(
    story,
    module_name: str,
    *,
    data_sources: str,
    note: str = "",
    muted_color,
    border_color,
):
    """Unified PVMath report footer across SiteIQ, TopoIQ, and YieldIQ."""
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=border_color))
    story.append(Spacer(1, 0.2 * cm))
    footer_text = PVMATH_FOOTER_TEMPLATE.format(
        module=module_name,
        note=note,
        sources=data_sources,
    )
    story.append(Paragraph(
        footer_text,
        ParagraphStyle(
            "pvm_footer",
            fontSize=7,
            textColor=muted_color,
            leading=10,
        ),
    ))
