"""Shared PDF helpers for SiteIQ, TopoIQ, and YieldIQ reports."""
from __future__ import annotations

import re

from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import HRFlowable, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm

_EMOJI_PATTERN = re.compile(
    r"[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F600-\U0001F64F"
    r"\u2600-\u26FF\u2700-\u27BF\uFE0F"
    r"✅⚠️❌🟢🟡🟠🔴⚠★]+"
)

SITEIQ_DISCLAIMER_BODY = (
    "This report provides preliminary site screening for internal go/no-go and early "
    "client discussions only. Solar data from PVGIS JRC; terrain from satellite DEM "
    "(indicative unless TopoIQ-confirmed); flood risk is an elevation heuristic, not "
    "hydraulic modelling; regulatory flags are indicative OSM-based checks, not "
    "permitting diligence. PVMath does not claim bankability. A full engineering study, "
    "site survey, permitting review, and certified energy yield assessment are required "
    "before financing, EPC contract, or final investment decision."
)

PVMATH_FOOTER_TEMPLATE = (
    "Generated by {module} — PVMath Solar Site Intelligence Platform "
    "&nbsp;|&nbsp; pvmath.com &nbsp;|&nbsp; contact@pvmath.com "
    "&nbsp;|&nbsp; For professional use only. {note}"
    "Data sources: {sources}."
)


def strip_pdf_label(text: str) -> str:
    """Remove emoji/icons from labels before PDF rendering (Helvetica-safe)."""
    if not text:
        return text
    cleaned = _EMOJI_PATTERN.sub("", str(text))
    return re.sub(r"\s+", " ", cleaned).strip()


def format_siteiq_companion_note(siteiq_run_cache: dict | None) -> str:
    """Rich SiteIQ companion text for TopoIQ PDF when screening cache exists."""
    if not siteiq_run_cache or not siteiq_run_cache.get("solar"):
        return (
            "Run SiteIQ on the same project for solar resource, flood risk, regulatory "
            "pathway, and overall site verdict. Terrain screening is one layer of the "
            "PVMath site intelligence workflow."
        )

    parts = ["SiteIQ screening has been run on this project."]
    score = siteiq_run_cache.get("pvmath_score")
    verdict = siteiq_run_cache.get("pvmath_verdict")
    if score is not None and verdict:
        parts.append(f"PVMath Site Suitability Score: {score}/100 ({verdict}).")

    solar = siteiq_run_cache.get("solar") or {}
    if solar.get("success") and solar.get("annual_ghi"):
        parts.append(f"Annual GHI: {solar['annual_ghi']:.0f} kWh/m²/yr.")

    terrain = siteiq_run_cache.get("terrain") or {}
    if terrain.get("success"):
        if terrain.get("topoiq_confirmed"):
            parts.append(
                f"Terrain (TopoIQ-linked): mean slope {terrain.get('mean_slope_pct', 0):.1f}%, "
                f"max {terrain.get('max_slope_pct', 0):.1f}%."
            )
        elif terrain.get("mean_slope_pct") is not None:
            parts.append(
                f"Terrain (indicative sample): mean slope {terrain['mean_slope_pct']:.1f}%."
            )

    rid = siteiq_run_cache.get("screening_report_id")
    if rid:
        parts.append(f"Screening ID: {rid}.")

    parts.append(
        "Open SiteIQ for flood risk, regulatory pathway, and the full site screening PDF."
    )
    return " ".join(parts)


def append_pdf_disclaimer(
    story,
    body: str,
    *,
    title: str = "IMPORTANT DISCLAIMER",
    border_color: str = "#f0b429",
    bg_color: str = "#fff8e6",
    text_color: str = "#7a4f00",
):
    """Append an amber-style disclaimer callout (YieldIQ pattern)."""
    story.append(Paragraph(
        title,
        ParagraphStyle(
            "disc_title",
            fontSize=9,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor(text_color),
            leading=12,
        ),
    ))
    story.append(Spacer(1, 0.15 * cm))
    disc_tbl = Table([[
        Paragraph(
            body,
            ParagraphStyle(
                "disc_body",
                fontSize=8.5,
                textColor=colors.HexColor(text_color),
                leading=13,
            ),
        ),
    ]], colWidths=["100%"])
    disc_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg_color)),
        ("BOX", (0, 0), (-1, -1), 1.5, colors.HexColor(border_color)),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(disc_tbl)


def append_pdf_footer(
    story,
    module_name: str,
    *,
    data_sources: str,
    note: str = "",
    muted_color,
    border_color,
):
    """Unified PVMath report footer across SiteIQ, TopoIQ, and YieldIQ."""
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=border_color))
    story.append(Spacer(1, 0.2 * cm))
    footer_text = PVMATH_FOOTER_TEMPLATE.format(
        module=module_name,
        note=note,
        sources=data_sources,
    )
    story.append(Paragraph(
        footer_text,
        ParagraphStyle(
            "pvm_footer",
            fontSize=7,
            textColor=muted_color,
            leading=10,
        ),
    ))
