"""Minimal screening PDF from gate analysis response (React / API)."""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from pvmath_pdf import SITEIQ_DISCLAIMER_BODY
from pvmath_geocode import pdf_escape


def build_screening_pdf(result: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    green = colors.HexColor("#1d9e52")

    def _cell(text: str) -> Paragraph:
        return Paragraph(pdf_escape(str(text)), styles["Normal"])

    story = []

    title = result.get("project_name") or "Site screening"
    story.append(Paragraph(f"<b>PVMath — Site Screening Report</b>", styles["Title"]))
    story.append(Paragraph(title, styles["Heading2"]))
    story.append(Spacer(1, 0.3 * cm))

    coords = result.get("coordinates") or {}
    lat = coords.get("lat", "")
    lon = coords.get("lon", "")
    story.append(Paragraph(f"Coordinates: {lat}, {lon}", styles["Normal"]))
    story.append(
        Paragraph(
            f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 0.4 * cm))

    verdict = result.get("verdict", "—")
    score = result.get("pvmath_score")
    score_txt = f" (score {score})" if score is not None else ""
    story.append(
        Paragraph(
            f'<font color="#157a40"><b>Verdict: {verdict}{score_txt}</b></font>',
            styles["Heading3"],
        )
    )
    story.append(Paragraph(result.get("verdict_detail", ""), styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    solar = result.get("solar") or {}
    terrain = result.get("terrain") or {}
    flood = result.get("flood") or {}
    regulatory = result.get("regulatory") or {}
    capacity = result.get("capacity") or {}

    terrain_src = terrain.get("terrain_source") or {}
    terrain_src_used = terrain.get("terrain_source_used") or terrain_src.get("source") or "unknown"
    terrain_src_note = terrain_src.get("disclaimer") or ""

    rows = [
        ["Metric", "Rating", "Detail"],
        ["Solar", solar.get("rating", "—"), solar.get("detail", "—")],
        [
            "Terrain",
            terrain.get("rating", "—"),
            (
                f"{terrain.get('detail', '—')} "
                f"(source: {terrain_src_used}; {terrain_src_note})"
            ).strip(),
        ],
        ["Flood", flood.get("risk", "—"), flood.get("detail", "—")],
        ["Regulatory", regulatory.get("status", "—"), regulatory.get("note", "—")],
        [
            "Capacity",
            capacity.get("mwp_range", "—"),
            capacity.get("mwh_range", "—"),
        ],
    ]
    table = Table([[ _cell(c) for c in row] for row in rows], colWidths=[4 * cm, 3.5 * cm, 9 * cm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), green),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d4e0d4")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f7f5")]),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph(f"<i>{SITEIQ_DISCLAIMER_BODY}</i>", styles["Normal"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(
        Paragraph(
            "Generated by PVMath — Solar Site Intelligence Platform | For professional use only.",
            styles["Normal"],
        )
    )

    doc.build(story)
    return buf.getvalue()
